USE adlister_db;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS ads;


CREATE TABLE users(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(100),
  email VARCHAR(50),
  password VARCHAR(30),
  PRIMARY KEY (id),
  UNIQUE (email)
);


CREATE TABLE ads(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(200) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users (id)
  ON DELETE CASCADE
);